### ISSUE TITLE
Supported Capabilities 

### ISSUE THREAD

**Issue by valinprogress** [FlaUI/FlaUI.WebDriver#14]
## Description

In WindowsDriver there are capabilities, such as "waitForAppLaunch", "newCommandTimeout", that as per documentation are not supported by FlaUI.WebDriver. in particular "newCommandTimeout" would be important when dealing with several drivers running.

## Environment

.NET 6 with C#
Appium server version 2.5.1
dotnet-client: Appium.WebDriver 5.0.0-rc.6
Selenium.WebDriver 4.18.1
appium-windows-driver
OS Windows 11
npm 10.5.0
Windows Application

Thank you

**Comment by aristotelos** [comment]
@valinprogress I don't really like the `ms:waitForAppLaunch` capability because it is custom and I am not so sure of the purpose. Why would you want to wait before attaching the session? Can't we use [the WebDriver 2 `pageLoad` timeout](https://www.w3.org/TR/webdriver2/#dfn-page-load-timeout) to do something similar?

**Comment by aristotelos** [comment]
Released support for `appium:newCommandTimeout` with https://github.com/FlaUI/FlaUI.WebDriver/releases/tag/v0.1.1 now!
