### ISSUE TITLE
Element Send Keys does not follow spec.

### ISSUE THREAD

**Issue by grokys** [FlaUI/FlaUI.WebDriver#32]
It simply sets `TetxBox` text, which is obviously incorrect according to https://www.w3.org/TR/webdriver2/#element-send-keys:

https://github.com/FlaUI/FlaUI.WebDriver/blob/main/src/FlaUI.WebDriver/Controllers/ElementController.cs#L182

I have started work on this but the process outlined by the spec requires a number of things that are currently not implemented, such as input sources. Not sure how closely the spec should be followed, or whether an initial "good enough for now" PR would be accepted.

**Comment by aristotelos** [comment]
I agree this should be fixed. Staying as close as possible to the specification gives most clarity for implementers in my opinion - unless there are clear reasons not to, for example because the spec assumes a web browser and we are using Windows UI automation. I have skipped over the implementation of input sources so far, but I would recommend creating an InputSource class or struct so that it leaves less room for misinterpretation of the specification.

**Comment by grokys** [comment]
Thanks - I actually already started on this last night and indeed I decided to follow the spec as closely as possible.
